language: node_js

node_js:
  - '6'

env:
  - workerCount=3

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential make python software-properties-common
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get install -y gcc-snapshot gcc-6 g++-6
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6 && \

matrix:
  fast_finish: true

install:
  - npm uninstall typescript
  - npm uninstall tslint
  - npm install -g node-gyp
  - npm install
  - npm update

cache:
  directories:
    - node_modules

git:
  depth: 1
