language: node_js

node_js:
  - '6'

env:
  - workerCount=3

matrix:
  fast_finish: true

install:
  - npm uninstall typescript
  - npm uninstall tslint
  - npm install -g node-gyp
  - npm install

cache:
  directories:
    - node_modules

git:
  depth: 1

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
